// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountRequest struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type AccountResponse struct {
	ProviderCode         string   `protobuf:"bytes,1,opt,name=providerCode,proto3" json:"providerCode,omitempty"`
	RegionCode           string   `protobuf:"bytes,2,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{1}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetProviderCode() string {
	if m != nil {
		return m.ProviderCode
	}
	return ""
}

func (m *AccountResponse) GetRegionCode() string {
	if m != nil {
		return m.RegionCode
	}
	return ""
}

type ProductsResponse struct {
	Items                []*ProductItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProductsResponse) Reset()         { *m = ProductsResponse{} }
func (m *ProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ProductsResponse) ProtoMessage()    {}
func (*ProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{2}
}

func (m *ProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductsResponse.Unmarshal(m, b)
}
func (m *ProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductsResponse.Marshal(b, m, deterministic)
}
func (m *ProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductsResponse.Merge(m, src)
}
func (m *ProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ProductsResponse.Size(m)
}
func (m *ProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductsResponse proto.InternalMessageInfo

func (m *ProductsResponse) GetItems() []*ProductItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type ProductItem struct {
	ProviderCode         string   `protobuf:"bytes,1,opt,name=providerCode,proto3" json:"providerCode,omitempty"`
	RegionCode           string   `protobuf:"bytes,2,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	SkuCode              string   `protobuf:"bytes,3,opt,name=skuCode,proto3" json:"skuCode,omitempty"`
	Minimum              *Price   `protobuf:"bytes,4,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum              *Price   `protobuf:"bytes,5,opt,name=maximum,proto3" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductItem) Reset()         { *m = ProductItem{} }
func (m *ProductItem) String() string { return proto.CompactTextString(m) }
func (*ProductItem) ProtoMessage()    {}
func (*ProductItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{3}
}

func (m *ProductItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductItem.Unmarshal(m, b)
}
func (m *ProductItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductItem.Marshal(b, m, deterministic)
}
func (m *ProductItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductItem.Merge(m, src)
}
func (m *ProductItem) XXX_Size() int {
	return xxx_messageInfo_ProductItem.Size(m)
}
func (m *ProductItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductItem.DiscardUnknown(m)
}

var xxx_messageInfo_ProductItem proto.InternalMessageInfo

func (m *ProductItem) GetProviderCode() string {
	if m != nil {
		return m.ProviderCode
	}
	return ""
}

func (m *ProductItem) GetRegionCode() string {
	if m != nil {
		return m.RegionCode
	}
	return ""
}

func (m *ProductItem) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *ProductItem) GetMinimum() *Price {
	if m != nil {
		return m.Minimum
	}
	return nil
}

func (m *ProductItem) GetMaximum() *Price {
	if m != nil {
		return m.Maximum
	}
	return nil
}

type Price struct {
	SendValue            float32  `protobuf:"fixed32,1,opt,name=sendValue,proto3" json:"sendValue,omitempty"`
	SendCurrencyIso      string   `protobuf:"bytes,2,opt,name=sendCurrencyIso,proto3" json:"sendCurrencyIso,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{4}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetSendValue() float32 {
	if m != nil {
		return m.SendValue
	}
	return 0
}

func (m *Price) GetSendCurrencyIso() string {
	if m != nil {
		return m.SendCurrencyIso
	}
	return ""
}

type TransferRequest struct {
	SkuCode              string   `protobuf:"bytes,1,opt,name=skuCode,proto3" json:"skuCode,omitempty"`
	SendValue            float32  `protobuf:"fixed32,2,opt,name=sendValue,proto3" json:"sendValue,omitempty"`
	SendCurrencyIso      string   `protobuf:"bytes,3,opt,name=sendCurrencyIso,proto3" json:"sendCurrencyIso,omitempty"`
	AccountNumber        string   `protobuf:"bytes,4,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	ValidateOnly         bool     `protobuf:"varint,5,opt,name=validateOnly,proto3" json:"validateOnly,omitempty"`
	DistributorRef       string   `protobuf:"bytes,6,opt,name=distributorRef,proto3" json:"distributorRef,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{5}
}

func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (m *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(m, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *TransferRequest) GetSendValue() float32 {
	if m != nil {
		return m.SendValue
	}
	return 0
}

func (m *TransferRequest) GetSendCurrencyIso() string {
	if m != nil {
		return m.SendCurrencyIso
	}
	return ""
}

func (m *TransferRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *TransferRequest) GetValidateOnly() bool {
	if m != nil {
		return m.ValidateOnly
	}
	return false
}

func (m *TransferRequest) GetDistributorRef() string {
	if m != nil {
		return m.DistributorRef
	}
	return ""
}

type TransferResponse struct {
	TransferRecord       *TransferRecord `protobuf:"bytes,1,opt,name=transferRecord,proto3" json:"transferRecord,omitempty"`
	ResultCode           float32         `protobuf:"fixed32,2,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCodes           []*ErrorCodes   `protobuf:"bytes,3,rep,name=errorCodes,proto3" json:"errorCodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TransferResponse) Reset()         { *m = TransferResponse{} }
func (m *TransferResponse) String() string { return proto.CompactTextString(m) }
func (*TransferResponse) ProtoMessage()    {}
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{6}
}

func (m *TransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferResponse.Unmarshal(m, b)
}
func (m *TransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferResponse.Marshal(b, m, deterministic)
}
func (m *TransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferResponse.Merge(m, src)
}
func (m *TransferResponse) XXX_Size() int {
	return xxx_messageInfo_TransferResponse.Size(m)
}
func (m *TransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransferResponse proto.InternalMessageInfo

func (m *TransferResponse) GetTransferRecord() *TransferRecord {
	if m != nil {
		return m.TransferRecord
	}
	return nil
}

func (m *TransferResponse) GetResultCode() float32 {
	if m != nil {
		return m.ResultCode
	}
	return 0
}

func (m *TransferResponse) GetErrorCodes() []*ErrorCodes {
	if m != nil {
		return m.ErrorCodes
	}
	return nil
}

type TransferRecord struct {
	TransferId           *TransferId    `protobuf:"bytes,1,opt,name=transferId,proto3" json:"transferId,omitempty"`
	SkuCode              string         `protobuf:"bytes,2,opt,name=skuCode,proto3" json:"skuCode,omitempty"`
	Price                *TransferPrice `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	CommissionApplied    float32        `protobuf:"fixed32,4,opt,name=commissionApplied,proto3" json:"commissionApplied,omitempty"`
	StartedUtc           string         `protobuf:"bytes,5,opt,name=startedUtc,proto3" json:"startedUtc,omitempty"`
	CompletedUtc         string         `protobuf:"bytes,6,opt,name=completedUtc,proto3" json:"completedUtc,omitempty"`
	ProcessingState      string         `protobuf:"bytes,7,opt,name=processingState,proto3" json:"processingState,omitempty"`
	ReceiptText          string         `protobuf:"bytes,8,opt,name=receiptText,proto3" json:"receiptText,omitempty"`
	AccountNumber        string         `protobuf:"bytes,9,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransferRecord) Reset()         { *m = TransferRecord{} }
func (m *TransferRecord) String() string { return proto.CompactTextString(m) }
func (*TransferRecord) ProtoMessage()    {}
func (*TransferRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{7}
}

func (m *TransferRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRecord.Unmarshal(m, b)
}
func (m *TransferRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRecord.Marshal(b, m, deterministic)
}
func (m *TransferRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRecord.Merge(m, src)
}
func (m *TransferRecord) XXX_Size() int {
	return xxx_messageInfo_TransferRecord.Size(m)
}
func (m *TransferRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRecord proto.InternalMessageInfo

func (m *TransferRecord) GetTransferId() *TransferId {
	if m != nil {
		return m.TransferId
	}
	return nil
}

func (m *TransferRecord) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *TransferRecord) GetPrice() *TransferPrice {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *TransferRecord) GetCommissionApplied() float32 {
	if m != nil {
		return m.CommissionApplied
	}
	return 0
}

func (m *TransferRecord) GetStartedUtc() string {
	if m != nil {
		return m.StartedUtc
	}
	return ""
}

func (m *TransferRecord) GetCompletedUtc() string {
	if m != nil {
		return m.CompletedUtc
	}
	return ""
}

func (m *TransferRecord) GetProcessingState() string {
	if m != nil {
		return m.ProcessingState
	}
	return ""
}

func (m *TransferRecord) GetReceiptText() string {
	if m != nil {
		return m.ReceiptText
	}
	return ""
}

func (m *TransferRecord) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

type TransferId struct {
	TransferRef          string   `protobuf:"bytes,1,opt,name=transferRef,proto3" json:"transferRef,omitempty"`
	DistributorRef       string   `protobuf:"bytes,2,opt,name=distributorRef,proto3" json:"distributorRef,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferId) Reset()         { *m = TransferId{} }
func (m *TransferId) String() string { return proto.CompactTextString(m) }
func (*TransferId) ProtoMessage()    {}
func (*TransferId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{8}
}

func (m *TransferId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferId.Unmarshal(m, b)
}
func (m *TransferId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferId.Marshal(b, m, deterministic)
}
func (m *TransferId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferId.Merge(m, src)
}
func (m *TransferId) XXX_Size() int {
	return xxx_messageInfo_TransferId.Size(m)
}
func (m *TransferId) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferId.DiscardUnknown(m)
}

var xxx_messageInfo_TransferId proto.InternalMessageInfo

func (m *TransferId) GetTransferRef() string {
	if m != nil {
		return m.TransferRef
	}
	return ""
}

func (m *TransferId) GetDistributorRef() string {
	if m != nil {
		return m.DistributorRef
	}
	return ""
}

type TransferPrice struct {
	CustomerFee              float32  `protobuf:"fixed32,1,opt,name=customerFee,proto3" json:"customerFee,omitempty"`
	DistributorFee           float32  `protobuf:"fixed32,2,opt,name=distributorFee,proto3" json:"distributorFee,omitempty"`
	ReceiveValue             float32  `protobuf:"fixed32,3,opt,name=receiveValue,proto3" json:"receiveValue,omitempty"`
	ReceiveCurrencyIso       string   `protobuf:"bytes,4,opt,name=receiveCurrencyIso,proto3" json:"receiveCurrencyIso,omitempty"`
	ReceiveValueExcludingTax float32  `protobuf:"fixed32,5,opt,name=receiveValueExcludingTax,proto3" json:"receiveValueExcludingTax,omitempty"`
	TaxRate                  float32  `protobuf:"fixed32,6,opt,name=taxRate,proto3" json:"taxRate,omitempty"`
	TaxName                  string   `protobuf:"bytes,7,opt,name=taxName,proto3" json:"taxName,omitempty"`
	TaxCalculation           string   `protobuf:"bytes,8,opt,name=taxCalculation,proto3" json:"taxCalculation,omitempty"`
	SendValue                float32  `protobuf:"fixed32,9,opt,name=sendValue,proto3" json:"sendValue,omitempty"`
	SendCurrencyIso          string   `protobuf:"bytes,10,opt,name=sendCurrencyIso,proto3" json:"sendCurrencyIso,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *TransferPrice) Reset()         { *m = TransferPrice{} }
func (m *TransferPrice) String() string { return proto.CompactTextString(m) }
func (*TransferPrice) ProtoMessage()    {}
func (*TransferPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{9}
}

func (m *TransferPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferPrice.Unmarshal(m, b)
}
func (m *TransferPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferPrice.Marshal(b, m, deterministic)
}
func (m *TransferPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferPrice.Merge(m, src)
}
func (m *TransferPrice) XXX_Size() int {
	return xxx_messageInfo_TransferPrice.Size(m)
}
func (m *TransferPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferPrice.DiscardUnknown(m)
}

var xxx_messageInfo_TransferPrice proto.InternalMessageInfo

func (m *TransferPrice) GetCustomerFee() float32 {
	if m != nil {
		return m.CustomerFee
	}
	return 0
}

func (m *TransferPrice) GetDistributorFee() float32 {
	if m != nil {
		return m.DistributorFee
	}
	return 0
}

func (m *TransferPrice) GetReceiveValue() float32 {
	if m != nil {
		return m.ReceiveValue
	}
	return 0
}

func (m *TransferPrice) GetReceiveCurrencyIso() string {
	if m != nil {
		return m.ReceiveCurrencyIso
	}
	return ""
}

func (m *TransferPrice) GetReceiveValueExcludingTax() float32 {
	if m != nil {
		return m.ReceiveValueExcludingTax
	}
	return 0
}

func (m *TransferPrice) GetTaxRate() float32 {
	if m != nil {
		return m.TaxRate
	}
	return 0
}

func (m *TransferPrice) GetTaxName() string {
	if m != nil {
		return m.TaxName
	}
	return ""
}

func (m *TransferPrice) GetTaxCalculation() string {
	if m != nil {
		return m.TaxCalculation
	}
	return ""
}

func (m *TransferPrice) GetSendValue() float32 {
	if m != nil {
		return m.SendValue
	}
	return 0
}

func (m *TransferPrice) GetSendCurrencyIso() string {
	if m != nil {
		return m.SendCurrencyIso
	}
	return ""
}

type ErrorCodes struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Context              string   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorCodes) Reset()         { *m = ErrorCodes{} }
func (m *ErrorCodes) String() string { return proto.CompactTextString(m) }
func (*ErrorCodes) ProtoMessage()    {}
func (*ErrorCodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{10}
}

func (m *ErrorCodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorCodes.Unmarshal(m, b)
}
func (m *ErrorCodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorCodes.Marshal(b, m, deterministic)
}
func (m *ErrorCodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorCodes.Merge(m, src)
}
func (m *ErrorCodes) XXX_Size() int {
	return xxx_messageInfo_ErrorCodes.Size(m)
}
func (m *ErrorCodes) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorCodes.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorCodes proto.InternalMessageInfo

func (m *ErrorCodes) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorCodes) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountRequest)(nil), "AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "AccountResponse")
	proto.RegisterType((*ProductsResponse)(nil), "ProductsResponse")
	proto.RegisterType((*ProductItem)(nil), "ProductItem")
	proto.RegisterType((*Price)(nil), "Price")
	proto.RegisterType((*TransferRequest)(nil), "TransferRequest")
	proto.RegisterType((*TransferResponse)(nil), "TransferResponse")
	proto.RegisterType((*TransferRecord)(nil), "TransferRecord")
	proto.RegisterType((*TransferId)(nil), "TransferId")
	proto.RegisterType((*TransferPrice)(nil), "TransferPrice")
	proto.RegisterType((*ErrorCodes)(nil), "ErrorCodes")
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor_ecf0878b123623e2) }

var fileDescriptor_ecf0878b123623e2 = []byte{
	// 764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0xc5, 0x0e, 0x09, 0xe4, 0x1a, 0x92, 0x30, 0x8b, 0x4f, 0x16, 0xfa, 0x54, 0x45, 0x16, 0xaa,
	0x22, 0xb5, 0x72, 0xa5, 0x94, 0xb6, 0x12, 0x3b, 0x44, 0x69, 0x15, 0xa9, 0x02, 0x64, 0x02, 0x7b,
	0x33, 0x1e, 0xd0, 0x08, 0x7b, 0xc6, 0x9d, 0x1f, 0x14, 0x1e, 0xa2, 0xfb, 0x3e, 0x42, 0x77, 0x7d,
	0xa6, 0x2e, 0xfa, 0x1e, 0xd5, 0x8c, 0xed, 0xc4, 0x36, 0xa9, 0xc4, 0xa2, 0x3b, 0xdf, 0x73, 0x8f,
	0x67, 0xe6, 0xce, 0x39, 0x73, 0x2f, 0x0c, 0x73, 0xc1, 0x15, 0x7f, 0x13, 0xe7, 0x34, 0xb4, 0x5f,
	0xc1, 0x04, 0x06, 0xc7, 0x18, 0x73, 0xcd, 0x54, 0x44, 0xbe, 0x6a, 0x22, 0x15, 0xfa, 0x0f, 0x7a,
	0x4c, 0x67, 0x37, 0x44, 0xf8, 0xce, 0xd8, 0x99, 0xf4, 0xa3, 0x32, 0x0a, 0xae, 0x60, 0xb8, 0x64,
	0xca, 0x9c, 0x33, 0x49, 0x50, 0x00, 0x3b, 0xb9, 0xe0, 0x0f, 0x34, 0x21, 0xe2, 0x84, 0x27, 0xa4,
	0xfc, 0xa1, 0x81, 0xa1, 0x17, 0x00, 0x82, 0xdc, 0x51, 0xce, 0x2c, 0xc3, 0xb5, 0x8c, 0x1a, 0x12,
	0xbc, 0x87, 0xd1, 0x85, 0xe0, 0x89, 0xc6, 0x4a, 0xd6, 0xd6, 0xed, 0x52, 0x45, 0x32, 0xe9, 0x3b,
	0xe3, 0xce, 0xc4, 0x9b, 0xee, 0x84, 0x25, 0x63, 0xa6, 0x48, 0x16, 0x15, 0xa9, 0xe0, 0xa7, 0x03,
	0x5e, 0x0d, 0xfe, 0x17, 0x67, 0x41, 0x3e, 0x6c, 0xc9, 0x7b, 0x6d, 0x93, 0x1d, 0x9b, 0xac, 0x42,
	0x34, 0x86, 0xad, 0x8c, 0x32, 0x9a, 0xe9, 0xcc, 0xdf, 0x1c, 0x3b, 0x13, 0x6f, 0xda, 0x0b, 0x2f,
	0x04, 0xc5, 0x24, 0xaa, 0x60, 0xcb, 0x88, 0x17, 0x96, 0xd1, 0x6d, 0x31, 0x0a, 0x38, 0x38, 0x87,
	0xae, 0x45, 0xd0, 0xff, 0xd0, 0x97, 0x84, 0x25, 0xd7, 0x71, 0xaa, 0x8b, 0x73, 0xba, 0xd1, 0x0a,
	0x40, 0x13, 0x18, 0x9a, 0xe0, 0x44, 0x0b, 0x41, 0x18, 0x7e, 0x9c, 0x49, 0x5e, 0x9e, 0xb4, 0x0d,
	0x07, 0xbf, 0x1d, 0x18, 0xce, 0x45, 0xcc, 0xe4, 0x2d, 0x11, 0x95, 0x7a, 0xb5, 0x12, 0x9c, 0x66,
	0x09, 0x8d, 0x5d, 0xdd, 0x67, 0xec, 0xda, 0x59, 0xbb, 0x2b, 0x3a, 0x80, 0xdd, 0xb8, 0xf0, 0xc1,
	0x59, 0x61, 0x93, 0x4d, 0xcb, 0x6b, 0x82, 0x46, 0x8e, 0x87, 0x38, 0xa5, 0x49, 0xac, 0xc8, 0x39,
	0x4b, 0x1f, 0xed, 0x9d, 0x6c, 0x47, 0x0d, 0x0c, 0xbd, 0x84, 0x41, 0x42, 0xa5, 0x12, 0xf4, 0x46,
	0x2b, 0x2e, 0x22, 0x72, 0xeb, 0xf7, 0xec, 0x52, 0x2d, 0x34, 0xf8, 0xee, 0xc0, 0x68, 0x55, 0x67,
	0xe9, 0x91, 0x0f, 0x30, 0x50, 0x4b, 0x0c, 0x73, 0x91, 0xd8, 0x7a, 0xbd, 0xe9, 0x30, 0x9c, 0x37,
	0xe0, 0xa8, 0x45, 0x2b, 0x4c, 0x20, 0x75, 0xaa, 0x96, 0x26, 0x70, 0xa3, 0x1a, 0x82, 0x5e, 0x01,
	0x10, 0x21, 0xb8, 0x75, 0x8c, 0xf4, 0x3b, 0xd6, 0x81, 0x5e, 0x78, 0xba, 0x84, 0xa2, 0x5a, 0x3a,
	0xf8, 0xe5, 0xc2, 0xa0, 0xb9, 0x9f, 0xf9, 0xbf, 0xda, 0x71, 0x56, 0x1d, 0xca, 0x5b, 0x1e, 0x6a,
	0x96, 0x44, 0xb5, 0x74, 0x5d, 0x2e, 0xb7, 0x29, 0xd7, 0x01, 0x74, 0x73, 0xe3, 0x16, 0x2b, 0x83,
	0x37, 0x1d, 0x2c, 0x57, 0x28, 0x5c, 0x55, 0x24, 0xd1, 0x6b, 0xd8, 0xc3, 0x3c, 0xcb, 0xa8, 0x94,
	0x94, 0xb3, 0xe3, 0x3c, 0x4f, 0x29, 0x49, 0xac, 0x20, 0x6e, 0xf4, 0x34, 0x61, 0x4a, 0x97, 0x2a,
	0x16, 0x8a, 0x24, 0x57, 0x0a, 0x5b, 0x49, 0xfa, 0x51, 0x0d, 0x31, 0xa2, 0x61, 0x9e, 0xe5, 0x29,
	0x29, 0x19, 0x85, 0x1c, 0x0d, 0xcc, 0x18, 0x25, 0x17, 0x1c, 0x13, 0x29, 0x29, 0xbb, 0xbb, 0x54,
	0xb1, 0x22, 0xfe, 0x56, 0x61, 0x94, 0x16, 0x8c, 0xc6, 0xe0, 0x09, 0x82, 0x09, 0xcd, 0xd5, 0x9c,
	0x2c, 0x94, 0xbf, 0x6d, 0x59, 0x75, 0xe8, 0xa9, 0x95, 0xfa, 0x6b, 0xac, 0x14, 0x5c, 0x03, 0xac,
	0x6e, 0xcf, 0xac, 0xba, 0x12, 0xf4, 0xb6, 0x34, 0x79, 0x1d, 0x5a, 0x63, 0x2b, 0x77, 0xad, 0xad,
	0xbe, 0x75, 0x60, 0xb7, 0x71, 0xa9, 0x66, 0x6d, 0xac, 0xa5, 0xe2, 0x19, 0x11, 0x9f, 0x48, 0xf5,
	0x34, 0xeb, 0x50, 0x6b, 0x6d, 0x43, 0x2a, 0x0c, 0xd4, 0x42, 0xcd, 0x4d, 0xda, 0x42, 0x1f, 0x48,
	0xf1, 0xde, 0x3a, 0x96, 0xd5, 0xc0, 0x50, 0x08, 0xa8, 0x8c, 0xeb, 0xaf, 0xae, 0x78, 0x4d, 0x6b,
	0x32, 0xe8, 0x08, 0xfc, 0xfa, 0xff, 0xa7, 0x0b, 0x9c, 0xea, 0x84, 0xb2, 0xbb, 0x79, 0xbc, 0xb0,
	0x5a, 0xba, 0xd1, 0x5f, 0xf3, 0xc6, 0x67, 0x2a, 0x5e, 0x44, 0x46, 0xad, 0x9e, 0xa5, 0x56, 0x61,
	0x99, 0x39, 0x8b, 0xb3, 0x4a, 0xc7, 0x2a, 0x34, 0xb5, 0xaa, 0x78, 0x71, 0x12, 0xa7, 0x58, 0xa7,
	0xb1, 0xa2, 0x9c, 0x95, 0x12, 0xb6, 0xd0, 0x66, 0x63, 0xe9, 0x3f, 0xa3, 0xb1, 0xc0, 0xfa, 0x76,
	0x76, 0x04, 0xb0, 0x7a, 0x65, 0x08, 0xc1, 0x26, 0x5e, 0x75, 0x31, 0xfb, 0x6d, 0xce, 0x8a, 0x39,
	0x53, 0xc6, 0x4d, 0xe5, 0x6b, 0x29, 0xc3, 0xe9, 0x0f, 0x07, 0x3a, 0x1f, 0x95, 0x46, 0x87, 0xb0,
	0x5b, 0x0e, 0xa9, 0x2f, 0x9c, 0xdf, 0xeb, 0x1c, 0x0d, 0xc3, 0xe6, 0x78, 0xdb, 0x1f, 0x85, 0xad,
	0x29, 0x16, 0x6c, 0xa0, 0x43, 0xf0, 0x3e, 0x13, 0x55, 0x8d, 0x21, 0xf4, 0x84, 0xb2, 0xbf, 0x17,
	0xb6, 0x67, 0x54, 0xb0, 0x81, 0xde, 0xc1, 0xce, 0x25, 0x61, 0x49, 0x65, 0x21, 0x34, 0x0a, 0x5b,
	0xcd, 0x78, 0x7f, 0x2f, 0x6c, 0xb7, 0xad, 0x60, 0xe3, 0xa6, 0x67, 0x07, 0xef, 0xdb, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x6e, 0x06, 0x66, 0x06, 0x8b, 0x07, 0x00, 0x00,
}
